# Files distributed to students (.ok & tests/ handled automatically)
sp21/project/project2.d: $(MATERIALS_DST)/sp21/project/project2/birthdays.csv
sp21/project/project2.d: $(MATERIALS_DST)/sp21/project/project2/cwhsb.csv
sp21/project/project2.d: $(MATERIALS_DST)/sp21/project/project2/cwhsb_modified.csv
sp21/project/project2.d: $(MATERIALS_DST)/sp21/project/project2/disag.csv
sp21/project/project2.d: $(MATERIALS_DST)/sp21/project/project2/earnings.tsv
sp21/project/project2.d: $(MATERIALS_DST)/sp21/project/project2/lottery.tsv
sp21/project/project2.d: $(MATERIALS_DST)/sp21/project/project2/one_row_cwhsb.png
sp21/project/project2.d: $(MATERIALS_DST)/sp21/project/project2/row_earnings.png
sp21/project/project2.d: $(MATERIALS_DST)/sp21/project/project2/sample.csv
sp21/project/project2.d: $(MATERIALS_DST)/sp21/project/project2/shape_of_curve.png